#
# Filename: clean_asm_features.py
# Author: Jun Xu
# Email: junx@cs.bu.edu
# Created Time: Wed 16 Mar 2016 01:39:23 PM EDT
# Description: This script is to clean the feature points.
#   The features are saved as features_manual.csv and features_asm.csv
#   under "results" directory. Also the image filenames are saved to
#   image_names.txt.
#

import csv
from os import listdir
from os import remove
from os.path import isfile
from os.path import join

# clean ground-truth feature points
dname = '../../asm/points_99/'
fnames = [ f for f in listdir(dname) if isfile(join(dname, f)) ]
fnames.sort()

fname = '../../results/image_names.txt'
try:
	remove(fname)
except OSError:
	pass

with open(fname, 'w') as f:
	for fname in fnames:
		f.write('%s\n' % fname)

features = []
for fname in fnames:
	with open(dname + fname) as f:
		feature = [ line.split() for i,line in enumerate(f) if i >= 3 and i <= 101 ]
	for axis in zip(*feature):
		features.append(list(axis))

fname = '../../results/features_manual.csv'
try:
	remove(fname)
except OSError:
	pass

with open(fname, 'w') as f:
	writer = csv.writer(f)
	writer.writerows(features)

# clean feature points generated by ASM
dname = '../../asm/points_asm/'
fnames = [ f for f in listdir(dname) if isfile(join(dname, f)) ]
fnames.sort()

features = []
for fname in fnames:
	with open(dname + fname) as f:
		feature = [ line.split() for i,line in enumerate(f) if i >= 3 and i <= 101 ]
	for axis in zip(*feature):
		features.append(list(axis))

fname = '../../results/features_asm.csv'
try:
	remove(fname)
except OSError:
	pass

with open(fname, 'w') as f:
	writer = csv.writer(f)
	writer.writerows(features)
